name: deploy-workflow

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  server:
    name: Server 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: |
          nohup bun main.js > server.log 2>&1 &

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment_output.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload Artifact
        id: upload_artifact 
        uses: actions/upload-pages-artifact@v3
        with: 
          path: ./public/

      - name: Deploy to GitHub Pages
        id: deploy_pages 
        uses: actions/deploy-pages@v4
        with:
          artifact: ${{ steps.upload_artifact.outputs.artifact_path }}

